extern SHIFTL 
extern SHIFTR 
extern SHIFT_TIMES 
extern FACTORIAL 
global main 
global end 
BLANK BLANK 
BLANK BLANK 
BLANK BLANK 
BLANK BLANK 
BLANK BLANK 
BLANK BLANK 
BLANK BLANK 
BLANK BLANK 
section .text 
main: READ 
value READ 
f_times READ 
SHIFT_TIMES LOAD 
value SUB 
max BRNEG 
UPDATE_MAX_8245486993943867437_1_bigger LOAD 
value STORE 
max UPDATE_MAX_8245486993943867437_1_bigger: 
BLANK BLANK 
BLANK LOAD 
max CALL 
SHIFTL STORE 
max LOAD 
f_times CALL 
FACTORIAL ADD 
max STORE 
max BR 
end end: 
PUT max 
STOP section 
.data max: 
.space value: 
.space f_times: 
.space EOF 
