extern SHIFTL 
extern SHIFTR 
extern SHIFT_TIMES 
extern FACTORIAL 
global main 
global end 
BLANK BLANK 
BLANK BLANK 
BLANK BLANK 
BLANK BLANK 
BLANK BLANK 
BLANK BLANK 
BLANK BLANK 
BLANK BLANK 
section .text 
main: READ 
read_value LOAD 
read_value SUB 
max BRNEG 
UPDATE_MAX_8245486993943867437_1_bigger LOAD 
read_value STORE 
max UPDATE_MAX_8245486993943867437_1_bigger: 
BLANK BLANK 
BLANK READ 
SHIFT_TIMES LOAD 
max CALL 
SHIFTL STORE 
max READ 
FAC LOAD 
FAC CALL 
FACTORIAL ADD 
max STORE 
max BR 
end end: 
PUT max 
STOP section 
.data read_value: 
.space FAC: 
.space max: 
.space EOF 
